[ WARN ] Failed to fetch value for field: Sym.Dev.SALES_SERVER
[ WARN ] Traceback (most recent call last):
  File "C:\RobotFramework\sap_testing\Execution\Access_Data.py", line 59, in get_data
    field_value = eval(command)
                  ^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
AttributeError: module 'Data.Symphony.Dev' has no attribute 'SALES_SERVER'. Did you mean: 'SAP_SERVER'?

[ WARN ] Failed to fetch value for field: Sym.Dev.SALES_SERVER
[ WARN ] Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] The parameter is incorrect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\RobotFramework\sap_testing\Execution\Access_Data.py", line 59, in get_data
    field_value = eval(command)
                  ^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
AttributeError: module 'Data.Symphony.Dev' has no attribute 'SALES_SERVER'. Did you mean: 'SAP_SERVER'?

