[ WARN ] Failed to fetch value for field: Sym.Dev.Execute
[ WARN ] Traceback (most recent call last):
  File "C:\RobotFramework\sap_testing\Execution\Access_Data.py", line 59, in get_data
    field_value = eval(command)
                  ^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
AttributeError: module 'Data.Symphony.Dev' has no attribute 'Execute'

[ WARN ] Taking screenshot failed: OSError: screen grab failed
Make sure tests are run with a physical or virtual display.
[ WARN ] Failed to fetch value for field: Sym.Dev.Execute
[ WARN ] Traceback (most recent call last):
  File "C:\RobotFramework\sap_testing\Tests\Resource\SAP_Tcode_Library.py", line 352, in get_element_type
    type = self.session.findById(element_id).type
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<COMObject <unknown>>", line 2, in findById
pywintypes.com_error: (-2147352567, 'Exception occurred.', (619, 'SAP Frontend Server', 'The control could not be found by id.', 'C:\\Program Files (x86)\\SAP\\FrontEnd\\SAPgui\\sapfront.HLP', 393215, 0), None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\RobotFramework\sap_testing\Tests\Resource\SAP_Tcode_Library.py", line 76, in click_element
    element_type = self.get_element_type(element_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\RobotFramework\sap_testing\Tests\Resource\SAP_Tcode_Library.py", line 357, in get_element_type
    raise ValueError(message)
ValueError: Cannot find element with id ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\RobotFramework\sap_testing\Execution\Access_Data.py", line 59, in get_data
    field_value = eval(command)
                  ^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
AttributeError: module 'Data.Symphony.Dev' has no attribute 'Execute'

