[ ERROR ] Error in file 'F:\Robotframework\sap_testing\Tests\Resource\SCC4.robot' on line 3: Library 'SAP_Tcode_Library.py' does not exist.
[ ERROR ] Error in file 'F:\Robotframework\sap_testing\Tests\Resource\SCC4.robot' on line 6: Library 'Merger.py' does not exist.
[ WARN ] Failed to fetch value for field: Sym.Dev.Heineken_SAP_SERVER
[ WARN ] Traceback (most recent call last):
  File "F:\Robotframework\sap_testing\Execution\Access_Data.py", line 58, in get_data
    field_value = eval(command)
                  ^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
AttributeError: module 'Data.Symphony.Dev' has no attribute 'Heineken_SAP_SERVER'

[ WARN ] Failed to fetch value for field: Sym.Dev.Heineken_SAP_SERVER
[ WARN ] Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] The parameter is incorrect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Robotframework\sap_testing\Execution\Access_Data.py", line 58, in get_data
    field_value = eval(command)
                  ^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
AttributeError: module 'Data.Symphony.Dev' has no attribute 'Heineken_SAP_SERVER'

